### ISSUE TITLE
Usage from README is incorrect

### ISSUE THREAD

**Issue by CyriacBr** [arcanis/clipanion#11]
Testing this snippet from the README throws multiple TypeScript compilation errors:
```ts
import {Cli, Command, Context} from 'clipanion';

class GreetCommand extends Command {
    @Command.Boolean(`-v,--verbose`)
    public verbose: boolean = false;

    @Command.String(`--name`)
    public name?: string;

    @Command.Path(`greet`)
    async execute(cli: Cli, context: Context) {
        if (typeof this.name === `undefined`) {
            context.stdout.write(`You're not registered.\n`);
        } else {
            context.stdout.write(`Hello, ${this.name}!\n`);
        }
    }
}
```

Errors are the following:
* `Module '"../../node_modules/clipanion/lib/advanced"' has no exported member 'Context'`

* `Property 'execute' in type 'GreetCommand' is not assignable to the same property in base type 'Command<BaseContext>'.
  Type '(cli: Cli<BaseContext>, context: any) => Promise<void>' is not assignable to type '() => Promise<number | void>'`

**Comment by arcanis** [comment]
I fixed the examples - `Context` is `BaseContext`, and both parameters from `execute` are now properties of the command classes.
