### ISSUE TITLE
Better support for `console.log`

### ISSUE THREAD

**Issue by Ayc0** [arcanis/clipanion#115]
The doc seems to be recommending to use `this.context.stdout.write` instead of `console.log`:

![image](https://user-images.githubusercontent.com/22725671/150139003-6e502565-2965-4813-a32a-09ab51bc40b6.png)

But those 2 don't do exactly the same things:

code |`console.log` | `stdout.write`
-|-|-
![image](https://user-images.githubusercontent.com/22725671/150139764-13498a85-8796-43a3-ab32-4da54ee52927.png) | ![image](https://user-images.githubusercontent.com/22725671/150139578-ecba546b-366d-436f-a42e-5d91360a7d51.png) | ![image](https://user-images.githubusercontent.com/22725671/150139666-7e173023-fb42-4b3b-9dfd-65b7cc332d53.png)
![image](https://user-images.githubusercontent.com/22725671/150139828-ab00f3e3-5570-45b0-a709-e9675c6e3b12.png) | ![image](https://user-images.githubusercontent.com/22725671/150139850-897f0c33-234b-4634-b60e-515c8bf6c2c7.png) |![image](https://user-images.githubusercontent.com/22725671/150140776-074e0cda-c282-4a65-9f48-77aa82a68f9d.png)
![image](https://user-images.githubusercontent.com/22725671/150140427-8eb6b7f4-8e87-4fcb-8049-f35048468f9c.png) | ![image](https://user-images.githubusercontent.com/22725671/150140471-6477d4d1-4b16-47a9-91da-b0cd0bff2a39.png)| ![image](https://user-images.githubusercontent.com/22725671/150140596-017aa1d3-2629-4d3b-8307-7f45011f4a1f.png)

Here there a plan to include a fully compatible `console` (like `this.context.console`) that would work with clipanion and that would be 100% compatible with the `console.*` APIs?

**Comment by merceyz** [comment]
You can set `enableCapture: true` to have Clipanion redirect `console.*` to the correct streams
https://mael.dev/clipanion/docs/contexts
https://github.com/arcanis/clipanion/pull/103

**Comment by Ayc0** [comment]
That's sweet!
I didn't know that.

Do you think we should add a link to this page, or say something like "We also recommend you to enable  `enableCapture: true` if you want to still use `console.log`" in this help box?
