### ISSUE TITLE
Add `details` property to `@Command.{String,Boolean,Array}`

### ISSUE THREAD

**Issue by ifiokjr** [arcanis/clipanion#12]
### Description

At the moment the documentation created for a cli command is based on the static `usage` property. It also shows the following auto generated line. 

`tsproj create [--template,-t #0] [--pkg,-p #0] [--template-library,-T #0] [--verbose] <name>`

I would like to propose that the `@Command` decorator properties adds a new option to provide a details string that is automatically added to the generated docs.

### Example

```ts
import { Command } from 'clipanion';

export class CreateCommand extends Command {
  public static usage = Command.Usage({
    description: 'Create a new TypeScript project.',
    category: 'Create',
  });

  @Command.String({ required: true, details: `The name you would like to give the created project` })
  public name: string = '';

  @Command.String('--template,-t', { details: 'The template to use for the provided project. Defaults to `minimal`', })
  public template: string = 'minimal';

  Command.Path('create')
  public async execute() {
    this.context.stdout.write(
      JSON.stringify({
        name: this.name,
        template: this.template,
      }),
    );
  }
}
```

Would output the following docs when run with the `-h` flag:

```
Create a new TypeScript project.

Usage:

$ tsproj create [--template,-t] <name>

Positional: 

    <name>                              the name you would like to give the created project

Options:

    --template <string>                 The template to use for the provided project. Defaults to `minimal`
```

I'm happy to help make this happen, but I might need a few pointers in the right direction.

**Comment by arcanis** [comment]
That seems like a good idea 👍

Imo the way to go would be to forward the details here (like we do for `hidden`):
https://github.com/arcanis/clipanion/blob/master/sources/advanced/Command.ts#L103

Then to expose a new `getOptionList` method on `CommandBuilder`:
https://github.com/arcanis/clipanion/blob/master/sources/core.ts#L604

The display itself will probably be in `getUsageByRegistration()` where you'll use the newly added method to retrieve the options and aggregate them into `positionals` / `options` sections:
https://github.com/arcanis/clipanion/blob/master/sources/advanced/Cli.ts#L322-L328

**Comment by ifiokjr** [comment]
Okay, I've had a quick glance and I'll see if I can create the PR soon.

**Comment by SamVerschueren** [comment]
We actually need this as well. I'll see if I can come up with a PR in the coming days.

@arcanis Do you prefer `details` or `description`? To me `description` feels better as it is describing the property.

**Comment by d3lm** [comment]
I would personally vote for `description` for the options.

**Comment by arcanis** [comment]
Description is better, as `details` is only intended for multiline documentation 👍

**Comment by cspotcode** [comment]
I'd also like to suggest we add option grouping while we're at it: https://yargs.js.org/docs/#api-reference-groupkeys-groupname

For example, my team has a CLI tool with some universal credential-related flags.  No matter what subcommand you're running, you can optionally specify one of about 3 or 4 credential-related flags.  We currently group them under a `Credentials` sub-heading in the `--help` output, which keeps them organized and separate from subcommand-specific flags.

I'm hoping to switch to clipanion from yargs, and this is one of the missing features we need.

@SamVerschueren feel free to ping me for a code review if it will help.

**Comment by SamVerschueren** [comment]
@cspotcode I guess that's a separate feature from this one so I'd suggest creating a new issue for that explaining how exactly you see the grouping as output for instance.

**Comment by cspotcode** [comment]
@SamVerschueren I submitted #35 that briefly explains the idea with some sample output from yargs, but I assume it'll need to be tweaked a bit to match clipanion's formatting.

**Comment by SamVerschueren** [comment]
@arcanis Should we hide options that don't have a description? Or just show them without?

**Comment by d3lm** [comment]
I'd say that all options are listed and the cell for those that have no description are just blank.

**Comment by arcanis** [comment]
I'd prefer to "hide" them from the listing, but keep them on the usage line (and for documented options it's the other way around, we'd remove them from the usage line). Basically, if we take `yarn add` as example:

## if nothing is documented:

```
Usage:

$ yarn add [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] ...
```

## if we document `--dev` and `--peer`:

```
Usage:

$ yarn add [-E,--exact] [-T,--tilde] [-C,--caret] ...

Other options:

-D,--dev     Adds the packages as dev dependencies
-P,--peer    Adds the packages as peer dependencies
```

## If we document all options:

```
Usage:

$ yarn add ...

Options:

-D,--dev     Adds the packages as dev dependencies
-P,--peer    Adds the packages as peer dependencies
-E,--exact   References the packages via fixed ranges
-T,--tilde   References the packages via a tilde range (~)
-C,--caret   References the packages via a caret range (^)
```

**Comment by SamVerschueren** [comment]
Ok, so this is what I have right now.

No options documented
![image](https://user-images.githubusercontent.com/1913805/91883606-f2b4e100-ec84-11ea-9c2b-929ffd0bc84d.png)

Verbose option documented
![image](https://user-images.githubusercontent.com/1913805/91883668-0ceebf00-ec85-11ea-847e-2bc38fd873fe.png)

Some questions that I have. 

1. If we have a `@Command.String('--name')`, do we want to show it as `--name` or as `--name #0` in the options list?
2. Do we want to document positional parameters as well? I would be ok to not do that (for now) as I might not see much value. And we didn't discuss how that would look as well. So I'm up for it if you want to, but I need to know how you guys see this.

**Comment by arcanis** [comment]
Nice!

> If we have a `@Command.String('--name')`, do we want to show it as `--name` or as `--name #0` in the options list?

I'd go with the second one, otherwise it won't be clear since the option won't be on the usage either.

> Do we want to document positional parameters as well

Let's ignore them - I think it's reasonable to expect them to be documented as part of the general details.

**Comment by d3lm** [comment]
Fully agree with what you said @arcanis on omitting options with no description, as well as ignoring positional parameters 👍.

Great work @SamVerschueren 👏  Looks slick!
