### ISSUE TITLE
can not turn off a boolean option / flag with default true value

### ISSUE THREAD

**Issue by magicdawn** [arcanis/clipanion#123]
```
metadata = Option.Boolean('--metadata', true, {
  description: 'keep metadata',
})
```

I have a Boolean option, and defaults to `true`, in case we want to turn off default true, when called `--metadata false`, It shows error like
```
Unknown Syntax Error: Extraneous positional argument ("false")
```

**Comment by d-fischer** [comment]
I think the correct usage would be `--no-metadata` then, [as documented](https://mael.dev/clipanion/docs/options#booleans).

**Comment by arcanis** [comment]
Indeed
