### ISSUE TITLE
Clipanion doesn't work with TypeScript 4.8

### ISSUE THREAD

**Issue by tmkn** [arcanis/clipanion#127]
The latest version of `clipanion`  (3.2.0-rc.11) doesn't work with the latest version of `TypeScript` (4.8).

# Reproduce

1. Use clipanion@3.2.0-rc11
2. Use TypeScript@4.8.2
3. Enable `strictNullChecks` in your code
4. Compile

## Expected Result
Compiles fine

## Result
Clipanion type check errors.

It's due to stricter generic check introduced in 4.8:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to

> Unconstrained Generics No Longer Assignable to `{}`
> 
> In TypeScript 4.8, for projects with strictNullChecks enabled, TypeScript will now correctly issue an error when an unconstrained type parameter is used in a position where null or undefined are not legal values. That will include any type that expects {}, object, or an object type with all-optional properties.

Clipanion now errors because the first parameter of `WithArity` is restricted with `Type extends { length?: number; }`
![clipanion3](https://user-images.githubusercontent.com/2671613/188282310-aa31f2d5-8e7e-4b3f-bfe3-041cf4b809a1.PNG)
But in a lot of places it gets non restricted generics
![clipanion2](https://user-images.githubusercontent.com/2671613/188282287-3b94df9a-463f-478c-b00f-0fb89317ddbe.PNG)

Which results in these errors:
![clipanion1](https://user-images.githubusercontent.com/2671613/188282282-d5fb2423-79aa-4dba-9c8c-079183773b3e.PNG)

It's possible to bypass this for now with `skipLibCheck` but unfortunately this turns off type checking for all libraries.

e:
Looks like adding `extends {}` like so gets rid of the errors:
![clipanion4](https://user-images.githubusercontent.com/2671613/188283053-95f349ed-fe73-4420-ab13-1c301c986af9.PNG)
However I cannot setup the dev environment to create a PR

**Comment by Ayc0** [comment]
A fix was shipped in https://github.com/arcanis/clipanion/pull/131 (version `3.2.0-rc.14`)

**Comment by tmkn** [comment]
👏 can confirm, works fine again
