### ISSUE TITLE
Support for default-enabled boolean command options

### ISSUE THREAD

**Issue by albertvaka** [arcanis/clipanion#143]
I want my users to be able to disable certain behavior in my CLI, by passing `--no-<something>`. 

Currently I can do that by adding a boolean option, eg: `--no-my-optional-feature` and store that as `noMyOptionalFeature` boolean. But then in my code I have to do double negations: `if (!noMyOptionalFeature) { enableOptionalFeature(); }` because my boolean is `true` when I _don't_ want that feature enabled.

It would be nice to have support for positive boolean arguments that default to `true` and that can be disabled by default by prefixing them with `no-`. This way, also, if as a user I want to explicitly enable the optional feature I could also write `--my-optional-feature` (without the `no-` prefix) and that would also be a valid argument.

**Comment by merceyz** [comment]
This is already how `Option.Boolean` works;

```ts
import { Command, Option, runExit } from 'clipanion';

class Foo extends Command {
	optionalFeature = Option.Boolean(`--my-optional-feature`, true);

	async execute() {
		console.log(this.optionalFeature);

		return 0;
	}
}

runExit([Foo]);

```

```console
$ my-cli
true
$ my-cli --no-my-optional-feature
false
$ my-cli --my-optional-feature
true
```
