### ISSUE TITLE
Nested commands like `gh auth login`

### ISSUE THREAD

**Issue by talentlessguy** [arcanis/clipanion#152]
Hi, this is not a bug but a question. I couldn't find in the docs nor in issues (maybe my keywords are wrong) but I can't see how to implemented nested commands to be able to handle stuff like this:

```sh
$ gh auth login --foo=bar
$ gh auth logout
```

Where help would display different help messages for each command, aka `gh auth login --help` and writing `gh auth` would output an index of commands

I though of it being something like this:

```ts
class AuthCommand extends Command {
  static paths = [[`auth`]]
}

class LoginCommand extends AuthCommand {
  static paths = [[`login`]]

  foo = Option.String(`-f,--foo`)
  async execute() {
    this.context.stdout.write(`This is foo: ${this.foo}.\n`)
  }
}
```

**Comment by arcanis** [comment]
`paths` in an array of arrays, so you can define `[['auth', 'login']]` and the command will be available as `gh auth login`.
