### ISSUE TITLE
Running `yarn` after pulling errors

### ISSUE THREAD

**Issue by abarisain** [arcanis/clipanion#18]
Hello!

I'm getting

>➤ YN0018: │ typescript@patch:typescript@npm%3A3.7.4#builtin<compat/typescript>::version=3.7.4&hash=226bd1: The remote archive doesn't match the expected checksum

when running "yarn" after install.

I found https://github.com/yarnpkg/berry/issues/1142,  and `YARN_CHECKSUM_BEHAVIOR=update yarn` fixes it. I'm opening an issue because I'm not sure if this is an appropriate fix to commit.

**Comment by paul-soporan** [comment]
I also got this error when installing dependencies after I cloned the repo. I'd say you should ignore it for now, as I upgraded everything (including Yarn and Typescript) in this PR: #19. The version of Yarn that Clipanion currently uses is 10 versions old, so there's a chance that this has already been fixed upstream.

**Comment by abarisain** [comment]
Yeah I'm just locally reverting yarn.lock and all is fine
