### ISSUE TITLE
TypeScript types do not match actually exported objects

### ISSUE THREAD

**Issue by borekb** [arcanis/clipanion#2]
[TypeScript types](https://github.com/arcanis/clipanion/blob/2e9a22bf6cf5a02ac0ed91d2cbab51022c7f5773/index.d.ts) seem to export something different than [`sources/core/index.js`](https://github.com/arcanis/clipanion/blob/2e9a22bf6cf5a02ac0ed91d2cbab51022c7f5773/sources/core/index.js). For example, this is in the README:

```js
const { clipanion } = require('clipanion');

clipanion.command(...);
```

But this is what actually works in a TypeScript project:

```ts
import { Clipanion } from 'clipanion';

const clipanion = new Clipanion();
clipanion.command(...);
```

I'm happy to submit a PR but wanted to discuss first what is actually correct – should types be updated or exports in `index.js`?

**Comment by arcanis** [comment]
No you're right, it should probably be:

```ts
export const clipanion: Clipanion;
```

Instead of

```ts
export default Clipanion;
```
