### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by TheGrimSilence** [arcanis/clipanion#28]
Hi! I just wanted to say thank you for building Clipanion. I know that probably seems weird, but long story short, I hated Commander, and definitely hate method chaining. I set out to build a class-based command-line framework called Strategos but I could never get the logic figured out in a scalable way. See, a simple for-loop was never going to cut it. I had a few ideas, highly inspired by Minecraft's Command system, `BaseCommand`, `AddCommand`, etc...

A finite state machine? Never would have thought about it! Anyway, I struggled for a long time as a self-taught developer with lackluster CS skills, and Clipanion solved my hatred of Commander.

So, thank you.

**Comment by arcanis** [comment]
Thanks, I'm glad to hear that! The original version of Clipanion was [quite different](https://github.com/arcanis/clipanion/tree/v1#usage), but over time I noticed it was starting to become [quite a beast](https://github.com/arcanis/clipanion/blob/v1/sources/core/Clipanion.js#L368-L733) and wouldn't be maintainable on the long run. I believe the current model is much saner 😃

If you like this "functional toolkit" approach, I think you'll also like [Typanion](https://github.com/arcanis/typanion) which is still a bit experimental but that I intend to be the definite type-safe validator library (to replace `yup` in the documentation, which has a few problems of its own).
