### ISSUE TITLE
Variadic options

### ISSUE THREAD

**Issue by elmpp** [arcanis/clipanion#32]
I'm trying to emulate the behaviour of the scaffolding tool [plop](https://plopjs.com/documentation/#bypassing-prompts-by-name-) where a freeform list of options may be supplied via the cli.

The way it's achieved there is to parse all options following `--` as a collection. Another approach could be just having a "strict: boolean" switch within  CommandClass that would collate all non-specified options as a collection (kinda like a variadic parameter).

Does this sound a suitable feature for clipanion?

**Comment by merceyz** [comment]
Sounds like the `Command.Proxy` type https://github.com/arcanis/clipanion/blob/a959b585f8433c4e8bb146789cf061e389c2169f/sources/advanced/Command.ts#L281-L296

**Comment by elmpp** [comment]
it does indeed!
