### ISSUE TITLE
Validation errors that make sense to end-user

### ISSUE THREAD

**Issue by cspotcode** [arcanis/clipanion#37]
Using the yup integration, I see that the validation errors refer to internal implementation details.  Ideally, the end-user would see errors referring to the `--flags` they provided rather than to the internal structure of the `Command` subclass.

Are there any plans to add those sorts of meaningful errors, or any constraints preventing this feature from being added?

**Comment by paul-soporan** [comment]
I think this can be closed as implemented in #69.
