### ISSUE TITLE
[Feature Request/Question] Using with dependency injection library

### ISSUE THREAD

**Issue by Bnaya** [arcanis/clipanion#49]
First, thanks for Clipanion and yarn 2!!

I want to add DI library, that will inject stuff into the constructor 
[InversifyJS](https://github.com/inversify/InversifyJS) or [tsyringe](https://github.com/microsoft/tsyringe)

In that context, I think we can see clipanion as "properties injector", and I want to add constructor injector  

I need to get in the middle of the "new commandClass" and then let clipanion do his thin'
https://github.com/arcanis/clipanion/blob/34968ed1c77b0fedc4e32b44981e54a357db62fe/sources/advanced/Cli.ts#L215-L216
Is there a way to "make it work" without modifying/patching clipanion?

Background:
The injection can be used for easier decoupling of logic, use less singletons, and make testing easier with out mocks in the modules level

The first thing I have in mind to put in the DI is config file and lookup.
pseudo code to emphasise what i mean:
```ts
@injectable()
class ConfigFile {
    constructor(@inject('clipanionContext'), context:  ClipanionContext) {
    }
    async getConfig(): IMyConfig {

        return ....;
    }
}

class SomeCommand extends Command {
    constructor(private configFile: ConfigFile) {
    }

    async exec() {
        const config = this.configFile.getConfig();

        this.context.stdout.write(chalk[config.color].(`Hello World\n`));
    }
}

cli.register(SomeCommand);

cli.commandCreationMiddleware({
    // This will be called when runExit is called.
    // Note, this is async, some async work can be done here
    // Not sure about error handing here thu
    async init(clipanionContext) {
        const inversifyContext = new inversify.Context();

        // make clipanionContext available in the DI as well
        inversifyContext.bind("ClipanionContext", clipanionContext);
        inversifyContext.bind(ConfigFile);

        // Opaque value that will be passed to provide
        return inversifyContext;
    },
    // Note, this is async, inversifyContext.get might have async providers.
    // Not sure about error handing here thu
    async provide(inversifyContext, klass) {
        return inversifyContext.get(klass);
    }
});

```

## Additional thoughts
The idea is somewhat influenced from nestjs,
With nestjs you can also define transformers and validators using decorators and keep the "controller" itself more about the command and less about the validations
https://docs.nestjs.com/pipes#transformation-use-case
Notable difference is that in nest each class member can be a "command"

**Comment by arcanis** [comment]
I'm not entirely sure I follow, but Clipanion uses regular ES6 classes, so you can do anything you want with them. In particular, you can implement a constructor if you need to, inherit them, or implement your own base command interfaces.

**Comment by Bnaya** [comment]
> I'm not entirely sure I follow, but Clipanion uses regular ES6 classes, so you can do anything you want with them. In particular, you can implement a constructor if you need to, inherit them, or implement your own base command interfaces.

I need to be the one that calls the "new" on the class, and also that Clipanion will be able to work with Promise that will be resolved to the command
While I can wrap my classes in some way, it will not make Clipanion to support async loading of commands

**Comment by arcanis** [comment]
Adding this isn't on my roadmap for the time being, so I prefer to close this for now.

**Comment by JanJakes** [comment]
@Bnaya One way to solve this is to create a base `DiAwareCommand` that would initialize the DI container and provide it to the child commands:

```ts
abstract class DiAwareCommand extends Command {
  protected appContext!: INestApplicationContext;

  async validateAndExecute(): Promise<number> {
    this.appContext = await NestFactory.createApplicationContext(AppCliModule, {
      logger: false,
    });

    try {
      return await super.validateAndExecute();
    } finally {
      await this.appContext.close();
    }
  }
}

export class TestCommand extends DiAwareCommand {
  name = Option.String();

  async execute() {
    const myService = this.appContext.get<MyService>(MyService);
    ...
  }
}
```

I know this is not registering the commands themselves in the DI and having constructor injection but on the other hand it's lazy (= you don't initialize all the dependencies for all the commands just by registering them).

An easy way to solve this on the Clipanion side would be to provide a user-configurable factory such as:
```ts
function (commandClass: CommandClass): Command;
```
Where the default implementation would be the current `const command = new commandClass();` but note that this would either be called also [in the register phase](https://github.com/arcanis/clipanion/blob/master/sources/advanced/Cli.ts#L195) or it wouldn't receive the deps on registration (= lazy and probably OK since registration seems to use the rather "static" parts or the class).

Since providing such a factory seems to be quite simple, is it anything you'd consider adding, @arcanis?
Thanks!
