### ISSUE TITLE
Confusing type inference for Option.String

### ISSUE THREAD

**Issue by kherock** [arcanis/clipanion#73]
It looks like my fix for this issue in #59 was partially reverted in b121c16 and I was wondering what the exact problem it was causing with implementing #68.

Currently, the type definitions act as if `tolerateBoolean`  is always `true` when an initial value is provided to `Option.String`. A workaround that works right now is to define `arity: 1` for the option.

![image](https://user-images.githubusercontent.com/4993980/105608143-3b725100-5d70-11eb-9142-11e843e43386.png)

**Comment by arcanis** [comment]
I've just checked, it seems to work. There was a problem with `tolerateBoolean: false` which should now be fixed in the trunk. If you still get a problem, please open a PR adding a failing test to `tests/inference.ts`.
