### ISSUE TITLE
Ability to see examples for the default command when CLI has only a single default command

### ISSUE THREAD

**Issue by cspotcode** [arcanis/clipanion#90]
For CLIs that only have a default command, and no others, it is not possible to do `<cli> <subcommand name> -h` to see the examples.

These CLIs should probably make the behavior of `<cli> -h` the same as if you had run `<cli> <subcommand name> -h`, which is to say, show the same detailed information about that command, including examples.

**Comment by arcanis** [comment]
Should be implemented in `3.0.0`.

**Comment by cspotcode** [comment]
Thanks!
