### ISSUE TITLE
Custom error (fail) hook

### ISSUE THREAD

**Issue by sachinraja** [arcanis/clipanion#94]
### Yargs Equivalent
Yargs allowed me to override the [`fail` method](https://yargs.js.org/docs/#api-reference-failfn-boolean) in which I could handle errors and have a custom format for the error message, rather than it just printing a default error message.

### Feature Description
The user can specify a method that runs when a command throws an error. This would override the default printing of an error message.

**Comment by arcanis** [comment]
You can override [`catch`](https://github.com/arcanis/clipanion/blob/master/sources/advanced/Command.ts#L118-L125)

**Comment by sachinraja** [comment]
Oh that seems to fit *almost* perfectly, but internal errors don't seem to go through it.

**Comment by hardfist** [comment]
After we move from yargs to clipanion, every thing works perfectly except the missing global uncaughtException hook(since clipanion doesn't expose exception and only expose exitCode)
